accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('', views.login_view, name="login"),
    path('logout/', views.logout_view, name = 'logout'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('shopping/', include('shopping.urls'))
]

shopping/urls.py
from django.urls import path

from . import views

app_name = 'shopping'

urlpatterns = [
    path('index', views.view_list, name="index"),
    path('add', views.add_list, name='add'),
    path('update', views.update_list, name="update")
]

accounts/models.py
from django.db import models

# Create your models here.

shopping/models.py
from django.db import models
from django.utils import timezone
import uuid

# Create your models here.
class ShoppingItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    userID = models.CharField(max_length = 100)
    itemName = models.CharField(max_length = 100)
    quantityItem = models.IntegerField()
    status = models.CharField(max_length = 50)
    date = models.DateField(default = timezone.now)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form' : form})

def login_view(request):
    if request.method=="POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('shopping:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {"form": form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

shopping/views.py
from django.shortcuts import render, redirect
from .models import ShoppingItem
from django.contrib.auth import get_user_model
from itertools import groupby
import uuid
# Create your views here.
def key_func(k):
    return k['date']
def view_list(request):
    if request.user.id != None:
        if request.method == "POST":
            data = []
            # print("Filter request", request)
            for objects in ShoppingItem.objects.all().filter(userID=request.user.id, date = request.POST['date']):
                # print("Filtered objects", objects)
                data.append({"itemName": objects.itemName, "quantity": objects.quantityItem, "date": objects.date,
                                 "status": objects.status,
                                 "pending": True if objects.status == "0" else False,
                                 "bought": True if objects.status == "1" else False,
                                 "not_available": True if objects.status == "2" else False, "uniqueID": objects.id})
            INFO = sorted(data, key=key_func)
            data_1 = []
            for key, value in groupby(INFO, key_func):
                a = []
                a.append(str(key))
                a.append(list(value))
                data_1.append(a)
            return render(request, 'shopping/index.html', context={"data": data_1})
        data = []
        for objects in ShoppingItem.objects.all().filter(userID=request.user.id):
            date_item = objects.date
            data.append({"itemName" : objects.itemName,"quantity": objects.quantityItem,"date": str(date_item), "status": objects.status,
                             "pending" : True if objects.status=="0" else False, "bought" : True if objects.status == "1" else False,
                             "not_available" : True if objects.status=="2" else False, "uniqueID": objects.id})
        INFO = sorted(data, key=key_func)
        data_1 = []
        for key, value in groupby(INFO, key_func):
            a = []
            a.append(str(key))
            a.append(list(value))
            data_1.append(a)
        return render(request, 'shopping/index.html', context={"data" : data_1})
    else:
        return redirect('accounts:login')

def add_list(request):
    if request.user.id != None:
        if request.method == "POST":
            current_user = request.user.id
            name = request.POST['item_name']
            quantity = request.POST['item_quantity']
            select_flag = request.POST['select_flag']
            date = request.POST['date']
            if len(name) == 0 or len(quantity) == 0 or len(date) == 0:
                return render(request, 'shopping/add.html', context = {"error" : "Fill all the quantity of form"})
            ShoppingItem(id=uuid.uuid4(), userID= current_user,itemName = name, quantityItem = quantity, status = select_flag, date = date).save()
            return redirect('shopping:index')
        return render(request, 'shopping/add.html')
    else:
        return redirect("accounts:login")

def update_list(request):
    if request.user.id != None:
        if request.POST['submit_item'] == "Delete":
            ShoppingItem.objects.all().get(id=request.POST["uniqueID"]).delete()
            return redirect('shopping:index')
        elif request.POST['submit_item'] == "Update":
            item_id = request.POST['uniqueID']
            item_name = request.POST['itemName']
            itemQuantity = request.POST['itemQuantity']
            itemStatus = request.POST['itemStatus']
            itemDate = request.POST['itemDate']
            context = {'uniqueID' : item_id, 'item_name' : item_name, "item_quantity" : itemQuantity, "item_status" : itemStatus, "item_date" : itemDate}
            # print("index context", context)
            return render(request, 'shopping/update.html', context)
        elif request.POST['submit_item'] == "Update_list":
            # print(request.POST["uniqueID"])
            item = ShoppingItem.objects.all().get(userID=request.user.id, id=request.POST["uniqueID"])
            item.itemName = request.POST['itemNameUpdate']
            item.quantityItem = int(request.POST['itemQuantityUpdate'])
            item.status = request.POST['itemStatusUpdate']
            item.date = request.POST['itemDateUpdate']
            item.save()
            return redirect('shopping:index')
        return render(request, 'shopping/update.html')
    else:
        return redirect("accounts:login")

templates/accounts/layout/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "posts/css/bootstrap.min.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <title>Django Blog</title>
</head>
<body class="container mt-5">
{% block content %}

{% endblock content %}
</body>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</html>

templates/accounts/login.html
{% extends "./layout/base.html" %}
{% load static %}
 
{% block content %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card">
        <div class="row no-gutters">
          <div class="col-md-5">
            <img src="{% static 'images/login.jpg' %}" alt="login" class="login-card-img">
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <p class="login-card-description">Sign into your account</p>
              <form action="{% url 'accounts:login' %}" method="post">
                  {% csrf_token %}
                  {{ form.non_field_errors }}
                  <div class="form-group">
                      {{ form.username.errors }}
                    <label>Email</label>
                      <br>
<!--                    <input type="email" name="email" id="email" class="form-control" placeholder="Email address">-->
                      {{form.username}}
                  </div>
                  <div class="form-group mb-4">
                      {{form.password.errors}}
                    <label>Password</label>
                      <br>
<!--                    <input type="password" name="password" id="password" class="form-control" placeholder="***********">-->
                      {{form.password}}
                  </div>
                  <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Login">
                </form>
                <p class="login-card-footer-text">Don't have an account? <br>
                    <a href="{% url 'accounts:signup' %}" class="text-reset">Register here</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    </main>
{% endblock content %}

templates/accounts/signup.html
{% extends "./layout/base.html" %}
{% load static %}
 
{% block content %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card">
        <div class="row no-gutters">
          <div class="col-md-7">
            <div class="card-body">
              <p class="login-card-description">Sign Up to your account</p>
              <form action="{% url 'accounts:signup' %}" method="post">
                  {% csrf_token %}
                  {{ form.non_field_errors }}
                  <div class="form-group">
                      {{form.username.errors}}
                    <label>User Name</label>
                      <br>
<!--                    <input type="email" name="email" id="email" class="form-control" placeholder="Email address">-->
                      {{form.username}}
                  </div>
                  <div class="form-group mb-4">
                      {{ form.password1.errors }}
                    <label>Password</label>
                      <br>
<!--                    <input type="password" name="password" id="password" class="form-control" placeholder="***********">-->
                      {{form.password1}}
                  </div>
                  <div class="form-group mb-4">
                      {{ form.password2.errors }}
                    <label>Confirm Password</label>
                      <br>
<!--                    <input type="password" name="password" id="password" class="form-control" placeholder="***********">-->
                      {{form.password2}}
                  </div>
                  <input name="signup" id="signup" class="btn btn-block login-btn mb-4" type="submit" value="Sign Up">
                </form>
                <p class="login-card-footer-text">Already have an account? <br>
                    <a href="{% url 'accounts:login' %}" class="text-reset">LogIn here</a></p>
            </div>
          </div>
            <div class="col-md-5">
            <img src="{% static 'images/login.jpg' %}" alt="login" class="login-card-img">
          </div>
        </div>
      </div>
    </div>
    </main>
{% endblock content %}

templates/shopping/add.html
{% load static %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Add List</title>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <style>
            .cardButtons{
                background: transparent;
                box-shadow: 0px 0px 0px transparent;
                border: 0px solid transparent;
                text-shadow: 0px 0px 0px transparent;
                color: black;
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a href="{% url 'shopping:index' %}" class="nav-link">Home</a>
                  </li>
                </ul>
              </div>
            {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post" class="form-inline my-2 my-lg-0">
                    {% csrf_token %}
                    <input class="cardButtons" type="submit" value="Logout">
                </form>
            {% endif %}
        </nav>
        <div class="container mt-5">
            <h1>Add Grocery List</h1>
            {% if error %}
            <h3> Fill all the fields of form </h3>
            {% endif %}
            <form action="{% url 'shopping:add' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Item name</label>
                    <input type="text" class="form-control" name="item_name" id="item_name" placeholder="Item name"/>
                </div>
                <div class="form-group">
                    <label>Item quantity</label>
                    <input type="text" class="form-control" name="item_quantity" id="item_quantity" placeholder="Item quantity"/>
                </div>
                <div class="form-group">
                    <label>Item status</label>
                    <select class="form-control" id="select_flag" name="select_flag">
                        <option value="0">PENDING</option>
                        <option value="1">BOUGHT</option>
                        <option value="2">NOT AVAILABLE</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" class="form-control" id="date" name="date" placeholder="Date">
                </div>
                <div class="form-group">
<!--                    <input type="submit" value="Add" id="submit" class="btn btn-danger">-->
                    <input type="submit" value="Add" id="Submit">
                </div>
            </form>
        </div>
    </body>
    <script>
        var today = new Date();
        document.getElementById("date").value = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2) + '-' + ('0' + today.getDate()).slice(-2);
    </script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

templates/shopping/index.html
{% load static %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>View List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <style>
            .cardButtons{
                background: transparent;
                box-shadow: 0px 0px 0px transparent;
                border: 0px solid transparent;
                text-shadow: 0px 0px 0px transparent;
                color: black;
                padding: 0;
                margin-right : 20%;
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a href="{% url 'shopping:index' %}" class="nav-link">Home</a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'shopping:add' %}" class="nav-link">Add Items</a>
                  </li>
                </ul>
              </div>
            {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post" class="form-inline my-2 my-lg-0">
                    {% csrf_token %}
                    <input class="cardButtons" type="submit" value="Logout">
                </form>
            {% endif %}
        </nav>
        <div class="container mt-5">
            <!-- top -->
            <div class="row">
                <div class="col-lg-8">
                    <h1>View Grocery List</h1>
                </div>
                <div class="col-lg-4 float-right">
                    <div class="row">
                        <form action="{% url 'shopping:index' %}" method="POST" >
                            {% csrf_token %}
                            <input type="hidden" name="date_filter" value="dateFilter">
                            <div class="col-lg-12">
                                <!-- Date Filtering-->
                                <input type="date" class="form-control" name="date" style="display : inline-block">
                                <input type="submit" class="btn btn-danger" value="filter" style="display: inline-block; float: right">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- // top -->
            <!-- Grocery Cards -->

                <!--- -->
                <!-- Loop This -->
                {% for a in data %}
                Date : {{a.0}}
                <div class="row mt-4">
                {% for item in a.1 %}
                <div class="col-lg-4">
                    <div class="card" style="margin-bottom : 20px;">
                        <div class="card-body">
                          <h5 class="card-title">{{item.itemName}}</h5>
                          <h6 class="card-subtitle mb-2 text-muted">{{item.quantity}} Kgs</h6>
                            {% if item.pending %}
                            <p class="text-info">PENDING</p>
                            {% endif %}
                            {% if item.bought %}
                            <p class="text-success">BOUGHT</p>
                            {% endif %}
                            {% if item.not_available %}
                            <p class="text-danger">NOT AVAILABLE</p>
                            {% endif %}
                            <br>
                            <form action="{% url 'shopping:update' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="uniqueID" value="{{item.uniqueID}}">
                                <input type="hidden" name="location" value="index">
                                <input type="hidden" name="itemName" value="{{item.itemName}}">
                                <input type="hidden" name="itemQuantity" value="{{item.quantity}}">
                                <input type="hidden" name="itemStatus" value={{item.status}}>
                                <input type="hidden" name="itemDate" value="{{item.date}}">
                                <button type="submit" name="submit_item" class="cardButtons" value="Update">Update</button>
                                <button type="submit" name="submit_item" class="cardButtons" value="Delete">Delete</button>
                            </form>
                        </div>
                      </div>
                </div>
                {% endfor %}
                    </div>
                {% endfor %}

        </div>
    </body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/shopping/update.html
{% load static %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <style>
            .cardButtons{
                background: transparent;
                box-shadow: 0px 0px 0px transparent;
                border: 0px solid transparent;
                text-shadow: 0px 0px 0px transparent;
                color: black;
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a href="{% url 'shopping:index' %}" class="nav-link">Home</a>
                  </li>
                </ul>
              </div>
            {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post" class="form-inline my-2 my-lg-0">
                    {% csrf_token %}
                    <input class="cardButtons" type="submit" value="Logout">
                </form>
            {% endif %}
        </nav>

        <div class="container mt-5">
            <h1>Update Grocery List</h1>
            <form action="{% url 'shopping:update' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="location" value="update">
                <input type="hidden" name="uniqueID" value="{{uniqueID}}">
                <div class="form-group">
                    <label>Item name</label>
                    <input type="text" class="form-control" placeholder="Item name" name="itemNameUpdate" value="{{item_name}}" />
                </div>
                <div class="form-group">
                    <label>Item quantity</label>
                    <input type="text" class="form-control" placeholder="Item quantity" name="itemQuantityUpdate" value="{{item_quantity}}"/>
                </div>
                <div class="form-group">
                    <label>Item status</label>
                    <select class="form-control" name="itemStatusUpdate" id="selectUpdate">
                        <option value="0">PENDING</option>
                        <option value="1">BOUGHT</option>
                        <option value="2">NOT AVAILABLE</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" class="form-control" placeholder="Date" name="itemDateUpdate" value="{{item_date}}">
                </div>

                <div class="form-group">
                    <input type="submit" value="Update_list" name="submit_item" class="btn btn-danger">
                </div>
            </form>
        </div>
    </body>
    <script>
        var status = {{item_status|safe}};
        $('#selectUpdate option:selected').removeAttr('selected');
        if(status == 0)
            $('#selectUpdate option:nth-child(1)').attr('selected','selected');
        else if(status == 1)
            $('#selectUpdate option:nth-child(2)').attr('selected','selected');
        else if(status == 2)
            $('#selectUpdate option:nth-child(3)').attr('selected','selected');
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>